const {
  REACT_APP_STRIPE_KEY_DEV,
  REACT_APP_S3_REGION_DEV,
  REACT_APP_S3_BUCKET_DEV,
  REACT_APP_API_GATEWAY_REGION_DEV,
  REACT_APP_API_GATEWAY_URL_DEV,
  REACT_APP_COGNITO_REGION_DEV,
  REACT_APP_COGNITO_USER_POOL_ID_DEV,
  REACT_APP_COGNITO_APP_CLIENT_ID_DEV,
  REACT_APP_COGNITO_IDENTITY_POOL_ID_DEV,

  REACT_APP_STRIPE_KEY,
  REACT_APP_S3_REGION,
  REACT_APP_S3_BUCKET,
  REACT_APP_API_GATEWAY_REGION,
  REACT_APP_API_GATEWAY_URL,
  REACT_APP_COGNITO_REGION,
  REACT_APP_COGNITO_USER_POOL_ID,
  REACT_APP_COGNITO_APP_CLIENT_ID,
  REACT_APP_COGNITO_IDENTITY_POOL_ID
} = process.env;

const dev = {
  STRIPE_KEY: REACT_APP_STRIPE_KEY_DEV,
  s3: {
    REGION: REACT_APP_S3_REGION_DEV,
    BUCKET: REACT_APP_S3_BUCKET_DEV
  },
  apiGateway: {
    REGION: REACT_APP_API_GATEWAY_REGION_DEV,
    URL: REACT_APP_API_GATEWAY_URL_DEV
  },
  cognito: {
    REGION: REACT_APP_COGNITO_REGION_DEV,
    USER_POOL_ID: REACT_APP_COGNITO_USER_POOL_ID_DEV,
    APP_CLIENT_ID: REACT_APP_COGNITO_APP_CLIENT_ID_DEV,
    IDENTITY_POOL_ID: REACT_APP_COGNITO_IDENTITY_POOL_ID_DEV
  }
};

const prod = {
  STRIPE_KEY: REACT_APP_STRIPE_KEY,
  s3: {
    REGION: REACT_APP_S3_REGION,
    BUCKET: REACT_APP_S3_BUCKET
  },
  apiGateway: {
    REGION: REACT_APP_API_GATEWAY_REGION,
    URL: REACT_APP_API_GATEWAY_URL
  },
  cognito: {
    REGION: REACT_APP_COGNITO_REGION,
    USER_POOL_ID: REACT_APP_COGNITO_USER_POOL_ID,
    APP_CLIENT_ID: REACT_APP_COGNITO_APP_CLIENT_ID,
    IDENTITY_POOL_ID: REACT_APP_COGNITO_IDENTITY_POOL_ID
  }
};

// Default to dev if not set
const config = process.env.REACT_APP_STAGE === 'prod'
  ? prod
  : dev;

export default {
  // Add common config values here
  MAX_ATTACHMENT_SIZE: 5000000,
  ...config
};
